accum_grad: 2
beta: 0.01
bf16: true
checkpoint: /notebooks/projects/CosyVoice/pretrained_models/CosyVoice2-0.5B/llm.pt
config: /notebooks/projects/CosyVoice/pretrained_models/CosyVoice2-0.5B/cosyvoice.yaml
cv_data: /notebooks/projects/tts2025/dpo_dataset.csv
deepscale: false
deepscale_config: null
deepspeed: false
deepspeed_config: null
dist_backend: nccl
dpo: false
dtype: fp32
epoch: -1
grad_clip: 5
log_interval: 100
max_epoch: 200
model: llm
model_dir: models
num_workers: 1
optim: adam
optim_conf:
  lr: 1.0e-05
per_device_train_batch_size: 16
pin_memory: false
prefetch: 100
save_per_step: -1
save_states: model_only
save_time: 26/03/2025 23:07:51
scheduler: warmuplr
scheduler_conf:
  warmup_steps: 25000
step: 0
tensorboard_dir: tensorboard
timeout: 60
train_data: /notebooks/projects/tts2025/dpo_dataset.csv
train_engine: torch_ddp
use_amp: true
